server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8


file:
  save:
    path: D:\Users\Administrator\Desktop\testServer

#  OriginalFilename: "D:\\Users\\Administrator\\Desktop\\efg" #注意长度与客户端路径长度匹配