post:
  url: "http://localhost:8080/upload"

file:
    UpLoadFileName: G:\desktop_job\client
    UpLoadCacheFile: G:\desktop_job\cache

upload:
  time: 9000

client:
  id: 20\efg

#spring:
#  servlet:
#    multipart:
#      max-file-size: 100MB
#      max-request-size: 100MB