post:
  url: "http://localhost:8080/upload"

file:
    OriginalFilename: "D:\\\\Users\\\\Administrator\\\\Desktop\\\\efg"

upload:
  time: 9000

client:
  id: 6

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB