post:
  url: "http://localhost:8080/upload"

file:
    UpLoadFileName: D:\Users\Administrator\Desktop\efg

upload:
  time: 9000

client:
  id: 20\efg

#spring:
#  servlet:
#    multipart:
#      max-file-size: 100MB
#      max-request-size: 100MB